### PR TITLE
Fix bad free

### LINKED ISSUE #29: BAD_FREE, in cpdb/cpdb-frontend.c:609 seems free(conf_dir) possible free a wrong memory
cpdb/cpdb-frontend.c:
```c++
    conf_dir = cpdbGetSysConfDir();
    if (conf_dir)
    {
        path = cpdbConcatPath(conf_dir, CPDB_DEFAULT_PRINTERS_FILE);
        printers = g_list_concat(printers, cpdbLoadDefaultPrinters(path));
        free(path);
        free(conf_dir);  // BAD_FREE
    } 
```

because `cpdbGetSysConfDir()` may return a static string:
```c++
    config_dir = "/etc/cpdb";  // static string
    if (access(config_dir, R_OK) == 0 || mkdir(config_dir, CPDB_SYSCONFDIR_PERM) == 0)
        return config_dir;
```

### PR DESCRIPTION
**Pull request by metabiswadeep**
Fixes #29

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@tillkamppeter

File: cpdb/cpdb.c [hunk 1]
```diff
@@ -229,13 +229,14 @@ char *cpdbGetUserConfDir()
     return NULL;
 }
 
-char *cpdbGetSysConfDir()
+char *cpdbGetSysConfDir(bool *is_dynamic)
```
Comment (michaelweghorn) [inline cpdb/cpdb.c:232]: API-wise, I think it'd be nicer to just always dynamically allocate the string, i.e. create a copy if necessary.

Comment (metabiswadeep) [reply cpdb/cpdb.c]: Done

File: cpdb/cpdb.c [hunk 2]
```diff
@@ -258,10 +258,11 @@ char *cpdbGetSysConfDir()
         free(env_xcd);
     }
         
-    config_dir = "/etc/cpdb";
-    if (access(config_dir, R_OK) == 0 || mkdir(config_dir, CPDB_SYSCONFDIR_PERM) == 0)
```
Comment (michaelweghorn) [inline cpdb/cpdb.c:262]: Was that check removed on purpose?

File: cpdb/cpdb.c [hunk 3]
```diff
@@ -258,10 +258,11 @@ char *cpdbGetSysConfDir()
...
-        return config_dir;
-
+    const char* static_path = "/etc/cpdb";
+    config_dir = (char*)malloc(strlen(static_path) + 1);
```
Comment (michaelweghorn) [inline cpdb/cpdb.c:262]: Can use `g_strdup` to simplify.

File: cpdb/cpdb.c (hunk 2 above)
Comment (metabiswadeep) [reply cpdb/cpdb.c:262]: No, it was a mistake. Brought it back.

File: cpdb/cpdb.c (hunk 3 above)
Comment (metabiswadeep) [reply cpdb/cpdb.c]: Done

File: cpdb/cpdb.c [hunk 4]
```diff
@@ -258,10 +258,12 @@ char *cpdbGetSysConfDir()
         free(env_xcd);
     }
         
-    config_dir = "/etc/cpdb";
+    const char* static_path = "/etc/cpdb";
+    config_dir = g_strdup(static_path);
     if (access(config_dir, R_OK) == 0 || mkdir(config_dir, CPDB_SYSCONFDIR_PERM) == 0)
```
Comment (michaelweghorn) [inline cpdb/cpdb.c:263]: Could be slightly simplified by using `static_path` for the checks, and only duplicating the string in the `if` block : `return g_strdup(static_path);`.

(No need to free below then).

There's still a leak of `config_dir` further up and a part of the implementation of this function looks  "suspicious" to me, but that's unrelated to this change. I'll submit a separate PR.

Comment (metabiswadeep) [reply cpdb/cpdb.c]: > Could

Done

Comment (metabiswadeep) [reply cpdb/cpdb.c]: > Could be slightly simplified by using `static_path` for the checks, and only duplicating the string in the `if` block : `return g_strdup(static_path);`.
> 
> (No need to free below then).
> 
> There's still a leak of `config_dir` further up and a part of the implementation of this function looks "suspicious" to me, but that's unrelated to this change. I'll submit a separate PR.

Done

File: cpdb/cpdb.c [hunk 5]
```diff
@@ -258,8 +258,9 @@ char *cpdbGetSysConfDir()
         free(env_xcd);
     }
         
-    config_dir = "/etc/cpdb";
-    if (access(config_dir, R_OK) == 0 || mkdir(config_dir, CPDB_SYSCONFDIR_PERM) == 0)
+    const char* static_path = "/etc/cpdb";
+    if (access(static_path, R_OK) == 0 || mkdir(static_path, CPDB_SYSCONFDIR_PERM) == 0)
+        config_dir = g_strdup(static_path);
         return config_dir;
```
Comment (michaelweghorn) [inline cpdb/cpdb.c:264]: Since there are no braces, only the `config_dir = g_strdup(static_path);` is part of the `if` block, the return statement is not, which means that a previously freed `config_dir` would be returned if the if check fails.

Need to either just `return g_strdup(static_path);` or add `{ ... }`.

**Review by michaelweghorn — CHANGES_REQUESTED** [review]

**Review by michaelweghorn — APPROVED** [review]
Looks good to me now, thanks.
